spring:
  application:
    name: auth-api
  datasource:
    url: jdbc:h2:mem:authdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    h2:
      console:
        enabled: true
        path: /h2-console

jwt:
  public-key: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAn+6Pdwzf5udSM27UIqe+
    EIYdSl1sxrKEb3eBkXQ5U0WSL8HgdmE4JV21v53ZkS7UmwZFqTmu4+gmVmlex6K8
    OC03tVOmzdZLfH16zMczRxgLaRLbFWp8fyDZUW8MAjPlpgRcX4FDM+V2z4NB+LI8
    NtvmX/cUyJX6SRtUnQrIWG5h4EBNcjLjMDHfbrYy1lgrTxwctQjs0Yss3MpGtC7t
    BAdZYS8tCICxN5BSWeYJS2CqBClfJVlnRzdP+pksNDaSnBaTvYI2psls+s2TXr/i
    /+EHgYv/z5XRY7TSGbjBkHjwy5sYQ/WDdnOgX8lVEaVki591gVHxRmfpKjh8j99I
    CwIDAQAB
    -----END PUBLIC KEY-----
  private-key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEAn+6Pdwzf5udSM27UIqe+EIYdSl1sxrKEb3eBkXQ5U0WSL8Hg
    dmE4JV21v53ZkS7UmwZFqTmu4+gmVmlex6K8OC03tVOmzdZLfH16zMczRxgLaRLb
    FWp8fyDZUW8MAjPlpgRcX4FDM+V2z4NB+LI8NtvmX/cUyJX6SRtUnQrIWG5h4EBN
    cjLjMDHfbrYy1lgrTxwctQjs0Yss3MpGtC7tBAdZYS8tCICxN5BSWeYJS2CqBClf
    JVlnRzdP+pksNDaSnBaTvYI2psls+s2TXr/i/+EHgYv/z5XRY7TSGbjBkHjwy5sY
    Q/WDdnOgX8lVEaVki591gVHxRmfpKjh8j99ICwIDAQABAoIBAD19LgF6nLcdJtiJ
    etwcHBIkTiyiQMkgJ5TnoJQ42DVw4SSlaNR6ymhrYA5c9SJBnBJCVhQbDmengN3m
    Qz+EDNOYZvu7Pr2S75DceZMz3z4tO23Zhwvz1gvWqFcL19Uc+OVcddtuSlUwmv5r
    m7ivZkE9SJSK3Z3FM+ZZsK10UNTWdWqoE0LWZ6cn6OtosFeB1hOK+RSWNNazykkg
    QfSlWjyWo3TYLfVSH452xYl332Ua6cmTfG0NKDVmIk+Jvkk/V393DFGwwfH33cje
    G1q0lroxJU5jC8r9gYQpvCgII3AbDWi22jCtP7v+UIGfRjA+87dNICxB5HE+dXlr
    bY3fRCkCgYEA8wvBMmRrxhwYSV/YIDlQb839B8+wcuKiraSYJ56xEoMJbdk+YazT
    ZCFIsxmtI8ULQsryup9kevhvqh+CWQie/qxecl8yUAgabWtG8tdfRy5wqGbPj6uP
    tI9NAL2z1a+OwL39cnR1/s89CYbknb8sC8kxIOOsLLi4ny5VOltZ5C0CgYEAqHTB
    IDSu/8Lqk0qU16c9N/W0ysszf/1PAC4z+tgsWggznWgFks2ErDqZJTpBE6QUKtaG
    9PwKL2iSjhMhfp6OO7rSMVpHIFn2sxG0z9h25So6Wy/8sqW2ZIBUWR5ybjz/37sn
    s7Gc/4ZoAySGt+AsWuaSTVPGIVfBu25ZwRbv6BcCgYEAi1+8RHeNzieiTcFmoOP9
    GoBXj7ksCFWq0ETI9D9ub50xNQsVWNHQz2S+2eXpgc+nK4BSPW7WIiaBcl9rUj89
    XfHen1uz8G0VKpYQM4YKHzmkZQ3ADTVmzTY4BCrFC88G38STqKTcXWjeKa5vP363
    dXLEd4XX4DV1ueLKARMNs2kCgYAmn25QJgQhm90QnD74Gt4MYIdtH53VMIzWa8F7
    N+kjU1ISOvFcMUbD/kNyp6KYEDyXfcw/izICoKVJcdVyJIRT6YebzSkVn8rST7L3
    HJhV/pKWqa/0fc4NyOaN8E8oO1AnSc/WgViPtY9PeSZyLjG9PbQ5ioWYy3gdszVc
    8hdbTQKBgF+qd3TV1NSLW9TS9KzC06msbWEPFCAaPPYBeZt27V/bsf6tVP9hFtxz
    gZ4Gf50iL18Agb6VKexgymOBBzgmvMK/kwOkrcWboJqOvWZpTpc4tKH2M7ubkIpQ
    Dc483bJtvPwnEH7qiJ60a1h5xxdzn59YbUetCaS3x7A6GwzWddlu
    -----END RSA PRIVATE KEY-----
  expiration: 86400000 # 24 hours in milliseconds
# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true

# Server Configuration
server:
  port: 8080

# Logging Configuration
logging:
  level:
    org.springframework.security: DEBUG
    com.auth.api: DEBUG