spring:
  application:
    name: auth-api
  datasource:
    url: jdbc:h2:mem:authdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    h2:
      console:
        enabled: true
        path: /h2-console

jwt:
  public-key: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkedGr9VTZsMEgKdCtIwp
    FAIJMWfQzQ6M83dr8zP3t5K6hZMyA6wlxSINcd/eiqyKFhZ9zVE6jTLuC5rypdpV
    mt4gPTBBVIBD+GVmHuGnm07ibg3Hv9iGRVWXl7QE8GJYzvvc2TEe9ULdlr42ZoBg
    zKmDT+k9v2ny5miEyNciacIiDUBYDhvjatjp4ZCVNwAoMYxWfZ4CqLvn9dL8VlyB
    FSGt9dRQqF4EeNemSxR6WP5R3Aga9oyZJjcuQJ7fFsmAAP7Ft4zeU6/KyM56mDKm
    6UAivyKrOnVwhfab1PJ4WeMSmCUR96Y+IIB40/DP4ZTM3H2qQesZMtEUU1+rpezB
    0QIDAQAB
    -----END PUBLIC KEY-----
  private-key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCR50av1VNmwwSA
    p0K0jCkUAgkxZ9DNDozzd2vzM/e3krqFkzIDrCXFIg1x396KrIoWFn3NUTqNMu4L
    mvKl2lWa3iA9MEFUgEP4ZWYe4aebTuJuDce/2IZFVZeXtATwYljO+9zZMR71Qt2W
    vjZmgGDMqYNP6T2/afLmaITI1yJpwiINQFgOG+Nq2OnhkJU3ACgxjFZ9ngKou+f1
    0vxWXIEVIa311FCoXgR416ZLFHpY/lHcCBr2jJkmNy5Ant8WyYAA/sW3jN5Tr8rI
    znqYMqbpQCK/Iqs6dXCF9pvU8nhZ4xKYJRH3pj4ggHjT8M/hlMzcfapB6xky0RRT
    X6ul7MHRAgMBAAECggEABvX4aAh5bib9CVZG1xjzbMJGxgCknuPZfaluO7AjBV25
    YF4ME3jHDzH3X5Nv/pW0u3u0jMhvTq/mA3pk+9yqxjS1Z7XsUqe768HgBAvSqeoy
    4KVE/mDKJyH/lXvqhb1rbJSU420gg6WpBLlrxwAg83gIN8Ec8mDk9xvNb0ze629b
    1zJrq0BeXyPGujlVBq6FbvGLDdo4zjE/zF2RqVEnd7wvEZcuythc5BofSQEIAXdi
    pTEY1w5rG7WhPw6J2w5jjYzv4Mw4dO/rFx0aemIbZppW4YDSdJfR97bMS6Blp8Ul
    eqcTsPN0653CoJ3bzBtnuW8tT1ZPHyVLmuHLIOgYcQKBgQDD7XCpTGXK63VOVESb
    WW0fz3yriq8dH4aJk/9m3oCCW8SqHo+DTyLDlLTxM1tievCSuAoO54vWN/+1arxm
    MICa+KtqJaVMCQVRV0rCxMzLBC8vIcrsEpoEF3P7Zj+wu5v4fYeIbddZ/3fyir4J
    i+TUSRO9breYz6heXn1IPUDPewKBgQC+o2R2gdg935vlE62iT7FDUsCTTxN4AY/s
    tvmgeevejkU0fnCMHj2RT2t2uEitHU/kwacXgjyEh8GZ23hJK+oIMJGTbmqwb8Ci
    IiIZrsdPOksgRwPMr5XkVjZRMimPKhyIfV4HFGml3qhhvPx78HHCQBlaOWn+W5ee
    eIlAXPHsIwKBgCoUyWnTWtmmkN9uAf5LysBWVDST6OCccM0D2ItDpt5Yz3iqb7CI
    QrM3MVXM7gfM1/brSF3DJamxBV71udlI+ZZPaqG1zDb0iQvbb9c9Za8FCw1YeLkT
    lbjjQKnyYCOZZ/qLG50V2nceA6k4W3C5d0CRIYhCS3SqxULfkJD/dvgZAoGANd3J
    R0sNJP6H+ESFLXXDKri5PWZ8o84dMs/I3TVWFn6ww1JuzsjEsMh2HweXUYMUzhiB
    9DySiQgrBiRjapmD+Whv2e67KruI/McUR5mBK7vW+nnWcwGyIuDRXEQGRjOp+E8k
    QG/eIkY14dgap5KbMj4Wa84JSxvqTZbVgWBB420CgYAd7yRupvsDd5ptRu4biZsE
    6ut54av+Al8o2koa1VvxbNfuTPHWaKh7Bm0L/zzdGjjO5FOFQm0HO1N9au9YFms6
    j2w+hXoXnjF2w6x7xp6S01zcwoPYKpyVUfEbMvPIZtAgfwMuCbO4EMuOXhQYDelu
    2Q+AZszW1ZzzAIKL8thHfA==
    -----END PRIVATE KEY-----
  expiration: 86400000 # 24 hours in milliseconds
# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true

# Server Configuration
server:
  port: 8080

# Logging Configuration
logging:
  level:
    org.springframework.security: DEBUG
    com.auth.api: DEBUG