version: '3.8'

services:
app:
  build: .
  ports:
    - "8080:8080"
  environment:
    - SPRING_PROFILES_ACTIVE=prod
  networks:
    - app-network

prometheus:
  image: prom/prometheus
  ports:
    - "9090:9090"
  volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
  networks:
    - app-network

grafana:
  image: grafana/grafana
  ports:
    - "3000:3000"
  environment:
    - GF_SECURITY_ADMIN_USER=admin
    - GF_SECURITY_ADMIN_PASSWORD=admin
  volumes:
    - grafana-data:/var/lib/grafana
  networks:
    - app-network
  depends_on:
    - prometheus

networks:
app-network:
  driver: bridge

volumes:
grafana-data: